# Define the agents

In [9]:
import random
import math
from numpy.core.shape_base import atleast_2d
import numpy as np
import pandas as pd
import matplotlib.ticker as ticker
import matplotlib.pyplot as plt


import matplotlib.pyplot as plt
from matplotlib.patches import FancyBboxPatch



In [35]:
# Import functions in the function file

%run trade_functions.ipynb


## define encounter matrix

In [36]:
economy_size=1000

In [37]:
import numpy as np

# Create a 100x100 matrix filled with 1s
matrix = np.ones((economy_size, economy_size))

# And  Set the diagonal elements to 0
np.fill_diagonal(matrix, 0)


## Define Economy A

In [38]:
agent_a = create_agent()
agent_a['id_list'] = [i for i in range(economy_size)]
agent_a['parameter']=[[3,3,3] for _ in range(economy_size)]
agent_a['money']=[2 for _ in range(economy_size)]
agent_a['gooda']=[1 for _ in range(economy_size)]
agent_a['goodb']=[2 for _ in range(economy_size)]


# Define Economy B

In [39]:
agent_b = create_agent()
agent_b['id_list'] = [i for i in range(economy_size)]
agent_b['parameter']=[[3,3,3] for _ in range(economy_size)]
agent_b['money']=[2 for _ in range(economy_size)]
agent_b['gooda']=[1 for _ in range(economy_size)]
agent_b['goodb']=[2 for _ in range(economy_size)]



In [40]:
agent_c = create_agent()
agent_c['id_list'] = [i for i in range(economy_size)]
agent_c['parameter']=[[2,2,2] for _ in range(economy_size)]
agent_c['money']=[2 for _ in range(economy_size)]
agent_c['gooda']=[1 for _ in range(economy_size)]
agent_c['goodb']=[2 for _ in range(economy_size)]

agent_c['constant']=[1 for _ in range(economy_size)]


#Defne  inhomogeneous economy

# metropolis

In [41]:
def onsager(agent1,agent2,length,size,t,f1,f2,flow):
  
  mla=agent1['money'].copy()
  gala=agent1['gooda'].copy()
  gbla=agent1['goodb'].copy()
  parametera=agent1['parameter'].copy()
    
  mlb=agent2['money'].copy()
  galb=agent2['gooda'].copy()
  gblb=agent2['goodb'].copy()
  parameterb=agent2['parameter'].copy()
  sum_etaa = sum(sublist[2] for sublist in parametera)
  sum_etab= sum(sublist[2] for sublist in parameterb)

 

  
  
  ga1_history=[]
  gb1_history=[]
  m1_history=[] 
  ga2_history=[]
  gb2_history=[]
  m2_history=[] 
  for i in range(length[0]):
    
    gala,gbla,mla=intra_trade(gala,gbla,mla,parametera,matrix,1,f1,f1)
    
    
    galb,gblb,mlb=intra_trade(galb,gblb,mlb,parameterb,matrix,1,f2,f2)
    

    
  
 
      
    
    
  
    


    
  for j in range(length[1]):
    
    gala,gbla,mla=intra_trade(gala,gbla,mla,parametera,matrix,1,f1,f1)
    gala,gbla,mla=direct_trade(gala,gbla,mla, 1, flow)
  
    
    galb,gblb,mlb=intra_trade(galb,gblb,mlb,parameterb,matrix,1,f2,f2)
    galb,gblb,mlb=direct_trade(galb,gblb,mlb, -1, flow)
  
    
    gala,gbla,mla,galb,gblb,mlb=inter_trade(gala,gbla,mla,galb,gblb,mlb,parametera,parameterb,matrix,size,t,f1,f2)

      
    ga1_history.append(sum(gala))
    gb1_history.append(sum(gbla))
    m1_history.append(sum(mla))
    ga2_history.append(sum(galb))
    gb2_history.append(sum(gblb))
    m2_history.append(sum(mlb))
   

  return ga1_history,gb1_history,m1_history,ga2_history,gb2_history,m2_history





In [42]:
def tester(agent1,agent2,gm,length,size,f1,f2):
  
  # we can update only money and good instead of build new agent set many times as they share same parameters
  mla=[gm[2]]*economy_size
  gala=[gm[0]]*economy_size
  gbla=[gm[1]]*economy_size
  
  parametera=agent2['parameter'].copy()
    
  mlb=agent1['money'].copy()
  galb=agent1['gooda'].copy()
  gblb=agent1['goodb'].copy()
  constant=agent1['constant'].copy()
  parameterb=agent1['parameter'].copy()
  sum_eta=np.sum(agent1['parameter'][2])
  sum_alpha1=np.sum(agent1['parameter'][0])
  sum_alpha2=np.sum(agent1['parameter'][1])
 

  

  ga2_history=[]
  gb2_history=[]
  m2_history=[] 

  for i in range(length[0]):
    
    gala,gbla,mla=intra_trade(gala,gbla,mla,parametera,matrix,1,f1,f1)
        
      
        
    galb,gblb,mlb=intra_trade(galb,gblb,mlb,parameterb,matrix,1,f2,f2)
    
  
    
    gala,gbla,mla,galb,gblb,mlb=test_trade(gala,gbla,mla,galb,gblb,mlb,parametera,parameterb,matrix,1,[1,1,1],f1,f2)
    #gala,gbla,mla,galb,gblb,mlb=test_trade(gala,gbla,mla,galb,gblb,mlb,parametera,parameterb,matrix,1,[0,1,0],f1,f2)
    #gala,gbla,mla,galb,gblb,mlb=test_trade(gala,gbla,mla,galb,gblb,mlb,parametera,parameterb,matrix,1,[0,0,1],f1,f2)
    

    
  
 
      
    
    
  
    

  for k in range (5):
      size=size*0.4
      length_size=length[1]
      
    
      for j in range(length_size):
        
        gala,gbla,mla=intra_trade(gala,gbla,mla,parametera,matrix,1,f1,f1)
        
      
        
        galb,gblb,mlb=intra_trade(galb,gblb,mlb,parameterb,matrix,1,f2,f2)
        
      
        
        gala,gbla,mla,galb,gblb,mlb=test_trade(gala,gbla,mla,galb,gblb,mlb,parametera,parameterb,matrix,size,[1,1,1],f1,f2)
        #gala,gbla,mla,galb,gblb,mlb=test_trade(gala,gbla,mla,galb,gblb,mlb,parametera,parameterb,matrix,size,[0,1,0],f1,f2)
        #gala,gbla,mla,galb,gblb,mlb=test_trade(gala,gbla,mla,galb,gblb,mlb,parametera,parameterb,matrix,size,[0,0,1],f1,f2)
    
        
       
        ga2_history.append(sum(galb))
        gb2_history.append(sum(gblb))
        m2_history.append(sum(mlb))
        

  return ga2_history,gb2_history,m2_history

In [43]:
def get_value(lst,sum_p,lenx):
    sub_list=lst[-lenx:]
    value_list=[ sum_p/x for x in sub_list]
    return np.mean(value_list)
    

In [44]:
def get_vgap(length1,length2,length3,range1,f1,flow):
    mga1,mgb1,mm1,mga2,mgb2,mm2=[],[],[],[],[],[]
    for i in range (length3[0]):
        ga1,gb1,m1,ga2,gb2,m2=onsager(agent_a,agent_b,length1,1,[1,1,1],f1,f1,flow)
        mga1.append(np.mean(ga1[-range1:])/economy_size)
        mga1.append(np.mean(ga1[-range1:])/economy_size)
        mgb1.append(np.mean(gb1[-range1:])/economy_size)
        mm1.append(np.mean(m1[-range1:])/economy_size)
        mga2.append(np.mean(ga2[-range1:])/economy_size)
        mgb2.append(np.mean(gb2[-range1:])/economy_size)
        mm2.append(np.mean(m2[-range1:])/economy_size)
    
    gm1=[np.mean(mga1),np.mean(mgb1),np.mean(mm1)]
    gm2=[np.mean(mga2),np.mean(mgb2),np.mean(mm2)]
    print(np.mean(mga1),np.mean(mgb1),np.mean(mm1),np.mean(mga2),np.mean(mgb2),np.mean(mm2))
    mvga,mvgb,mvm,mvga2,mvgb2,mvm2=[],[],[],[],[],[]
    for j in range(length3[1]):
        vga,vgb,vm=tester(agent_c,agent_a,gm1,length2,1,f1,utility_func_cd)
        vga2,vgb2,vm2=tester(agent_c,agent_b,gm2,length2,1,f1,utility_func_cd)
        mvga.append(get_value(vga,2000,100000))
        mvgb.append(get_value(vgb,2000,100000))
        mvm.append(get_value(vm,2000,100000))
        #print(mvga,mvgb,mvm)
        mvga2.append(get_value(vga2,2000,100000))
        mvgb2.append(get_value(vgb2,2000,100000))
        mvm2.append(get_value(vm2,2000,100000))
        #print(mvga2,mvgb2,mvm2)
        print(j)
    print('Gap',np.mean(mvga2)-np.mean(mvga),np.mean(mvgb2)-np.mean(mvgb),np.mean(mvm2)-np.mean(mvm))
    return np.mean(mvga2)-np.mean(mvga),np.mean(mvgb2)-np.mean(mvgb),np.mean(mvm2)-np.mean(mvm)
        

# Get Matrix

## Substitute economy

In [ ]:
# used mean of 40 samples. We tested it twice because of the device doesn't have enough memory

In [12]:
g11s,g21s,g31s=get_vgap([50000,100000],[50000,40000],[10,20],100000,utility_func_s,[0.03,0,0])

1.0288516466113344 2.0021390038238938 1.9996425544174705 0.9711483533886653 1.9978609961761062 2.0003574455825297
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
Gap 0.07983797325483777 0.011726171271256858 0.002475508515491942


In [14]:
g12s,g22s,g32s=get_vgap([50000,100000],[50000,40000],[10,20],100000,utility_func_s,[0,0.03,0])

1.0001737455011575 2.0286067438753848 2.0005734063389804 0.9998262544988423 1.9713932561246152 1.9994265936610192
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
Gap 0.010863483477390856 0.026493964934526604 0.0003751452294307178


In [17]:
g13s,g23s,g33s=get_vgap([50000,100000],[50000,40000],[10,20],100000,utility_func_s,[0,0,0.03])

1.001353232797919 2.001299880836009 2.0270609174958487 0.9986467672020811 1.9987001191639908 1.9729390825041508
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
Gap 0.003160258749439926 0.002379394937397805 0.04019735087379939


In [ ]:
# trail 2
g11s,g21s,g31s= 0.08283834113094213,0.009560554646995456, 0.0023063047307745332
g12s,g22s,g32s=0.010964830588907848, 0.028033828939122873, -0.0011403014406721201
g13s,g23s,g33s=0.00048044126159796363, -0.001595905822713739, 0.042230932930533926

In [22]:
g11s,g21s,g31s=get_vgap([50000,100000],[50000,40000],[10,20],100000,utility_func_s,[0.03,0,0])

1.0313699658279147 1.997869958248447 2.0018791909839657 0.968630034172085 2.0021300417515535 1.9981208090160343
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
Gap 0.08283834113094213 0.009560554646995456 0.0023063047307745332


In [23]:
g12s,g22s,g32s=get_vgap([50000,100000],[50000,40000],[10,20],100000,utility_func_s,[0,0.03,0])

0.9993538753820722 2.0295678887439124 1.9986433192161548 1.0006461246179277 1.9704321112560876 2.0013566807838448
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
Gap 0.010964830588907848 0.028033828939122873 -0.0011403014406721201


In [24]:
g13s,g23s,g33s=get_vgap([50000,100000],[50000,40000],[10,20],100000,utility_func_s,[0,0,0.03])

1.0006630157405787 1.998309984158076 2.0290803608895707 0.9993369842594213 2.001690015841924 1.970919639110429
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
Gap 0.00048044126159796363 -0.001595905822713739 0.042230932930533926


# Results

In [1]:
a11s,a21s,a31s= 0.07983797325483777 ,0.011726171271256858 ,0.002475508515491942
a12s,a22s,a32s=0.010863483477390856 ,0.026493964934526604, 0.0003751452294307178
a13s,a23s,a33s=-0.004472898690929039, 0.0005727389518912496 ,0.04524304513676114
#g13s,g23s,g33s==0.003160258749439926 0.002379394937397805 0.04019735087379939

In [2]:
b11s,b21s,b31s= 0.08283834113094213,0.009560554646995456, 0.0023063047307745332
b12s,b22s,b32s=0.010964830588907848, 0.028033828939122873, -0.0011403014406721201
b13s,b23s,b33s=0.00048044126159796363, -0.001595905822713739, 0.042230932930533926

In [3]:
g11s,g21s,g31s= a11s+b11s,a21s+b21s, a31s+b31s
g12s,g22s,g32s=a12s+b12s,a22s+b22s, a32s+b32s
g13s,g23s,g33s=a13s+b13s,a23s+b23s, a33s+b33s

In [4]:
# first 20 trails
a11c,a21c,a31c= 0.11913546955300625, -0.009905387485614536 ,0.001709460491951642
a12c,a22c,a32c=-0.008195932880528556, 0.017341025209249294 ,0.0006806136657060424
a13c,a23c,a33c=-0.001873079876412831 ,-9.543463564609667e-05 ,0.029029550299474627

In [5]:
b11c,b21c,b31c= 0.12090680710557056 ,-0.012066857856328994, -0.0038580555357341506
b12c,b22c,b32c=-0.006287921253495199, 0.02038029311578482, 0.00010455862003033722
b13c,b23c,b33c=0.0021894132751252293, -0.0018075529007800517 ,0.02487274574507703

In [6]:
c11c,c21c,c31c= 0.12699641691020602,-0.006078300707534123, 0.0014573028677378197
c12c,c22c,c32c=-0.013423325272235775, 0.021032953536144205, -0.0037091026706170815
c13c,c23c,c33c=-0.001562190395534735 ,0.0013116639868704372, 0.031174808090490336

In [7]:
g11c,g21c,g31c = a11c+b11c+c11c, a21c+b21c+c21c, a31c+b31c+c31c
g12c,g22c,g32c = a12c+b12c+c12c, a22c+b22c+c22c, a32c+b32c+c32c
g13c,g23c,g33c = a13c+b13c+c13c, a23c+b23c+c23c, a33c+b33c+c33c

## Complement Economy

In [ ]:
# Used mean of 60 samples

In [13]:
g11c,g21c,g31c=get_vgap([50000,100000],[50000,40000],[10,20],100000,utility_func_c,[0.02,0,0])

1.0190792767072185 1.9996863436878898 2.001652720606587 0.9809207232927817 2.0003136563121102 1.9983472793934134
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
Gap 0.11913546955300625 -0.009905387485614536 0.001709460491951642


In [18]:
g12c,g22c,g32c=get_vgap([50000,100000],[50000,40000],[10,20],100000,utility_func_c,[0,0.02,0])


1.0003052814747815 2.019337769589593 2.0004167621876645 0.9996947185252184 1.9806622304104067 1.999583237812335
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
Gap -0.008195932880528556 0.017341025209249294 0.0006806136657060424


In [19]:
g13c,g23c,g33c=get_vgap([50000,100000],[50000,40000],[10,20],100000,utility_func_c,[0,0,0.02])

1.000031555907502 2.000909103764648 2.0192493260166495 0.9999684440924981 1.9990908962353515 1.9807506739833503
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
Gap -0.001873079876412831 -9.543463564609667e-05 0.029029550299474627


In [12]:
g11c,g21c,g31c=get_vgap([50000,100000],[50000,40000],[10,20],100000,utility_func_c,[0.02,0,0])

1.0196507099612089 1.998240575780826 1.9993080063155215 0.9803492900387912 2.0017594242191743 2.0006919936844785
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
Gap 0.12090680710557056 -0.012066857856328994 -0.0038580555357341506


In [12]:
g12c,g22c,g32c=get_vgap([50000,100000],[50000,40000],[10,20],100000,utility_func_c,[0,0.02,0])

1.0006715214372044 2.0207226569582386 2.0010340350670868 0.9993284785627958 1.9792773430417614 1.9989659649329137
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
Gap -0.006287921253495199 0.02038029311578482 0.00010455862003033722


In [12]:
g13c,g23c,g33c=get_vgap([50000,100000],[50000,40000],[10,20],100000,utility_func_c,[0,0,0.02])

1.0002912459136426 1.9979884077819925 2.0174039949918408 0.9997087540863575 2.0020115922180075 1.9825960050081595
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
Gap 0.0021894132751252293 -0.0018075529007800517 0.02487274574507703


In [25]:
g11c,g21c,g31c=get_vgap([50000,100000],[50000,40000],[10,20],100000,utility_func_c,[0.02,0,0])

1.0205511883938756 2.0028864642612794 2.0004123775248175 0.9794488116061247 1.9971135357387204 1.9995876224751825
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
Gap 0.12699641691020602 -0.006078300707534123 0.0014573028677378197


In [26]:
g12c,g22c,g32c=get_vgap([50000,100000],[50000,40000],[10,20],100000,utility_func_c,[0,0.02,0])

0.9999829256936692 2.0197204876526653 1.9993655033962667 1.0000170743063308 1.9802795123473345 2.000634496603733
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
Gap -0.013423325272235775 0.021032953536144205 -0.0037091026706170815


In [27]:
g13c,g23c,g33c=get_vgap([50000,100000],[50000,40000],[10,20],100000,utility_func_c,[0,0,0.02])

1.0001599311095908 2.001062082909259 2.020026178760734 0.9998400688904091 1.9989379170907409 1.9799738212392661
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
Gap -0.001562190395534735 0.0013116639868704372 0.031174808090490336


## Calculate L matrix

## Substitute

In [10]:
matrixs=np.round(np.array([[g33s,g31s,g32s],[g13s,g11s,g12s],[g23s,g21s,g22s]])/(0.03*2),3)
print(matrixs)

[[ 1.458  0.08  -0.013]
 [-0.067  2.711  0.364]
 [-0.017  0.355  0.909]]


## Complement

In [11]:
np.set_printoptions(suppress=True)
matrixc=np.round(np.array([[g33c,g31c,g32c],[g13c,g11c,g12c],[g23c,g21c,g22c]])/(0.02*3),3)
print(matrixc)


[[ 1.418 -0.012 -0.049]
 [-0.021  6.117 -0.465]
 [-0.01  -0.468  0.979]]


# Test Matrix

In [13]:
va1s,va2s,va3s=get_vgap([50000,100000],[50000,40000],[10,20],100000,utility_func_s,[0.03,0.03,0])

1.0287485166458687 2.029864510218439 2.000877312804034 0.9712514833541313 1.9701354897815608 1.9991226871959662
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
Gap 0.08954899280257855 0.037079518483758234 0.0022997421392916273


In [12]:
vb1s,vb2s,vb3s=get_vgap([50000,100000],[50000,40000],[10,20],100000,utility_func_s,[0.03,-0.03,0])

1.0287640157905873 1.9687721921917667 1.9984282762362144 0.9712359842094129 2.031227807808233 2.0015717237637856
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
Gap 0.06710928410101347 -0.017247198892621718 -0.0005002718881363943


In [26]:
va1s,va2s,va3s=0.08954899280257855, 0.037079518483758234, 0.0022997421392916273
vb1s,vb2s,vb3s= 0.06710928410101347, -0.017247198892621718, -0.0005002718881363943

In [29]:
mvs1=np.round(np.array([va3s,va1s,va2s]),3)
mvs2=np.round(np.array([vb3s,vb1s,vb2s]),3)
tmvs1=np.round(np.array(np.dot(matrixs,[0,0.03,0.03])),3)
tmvs2=np.round(np.array(np.dot(matrixs,[0,0.03,-0.03])),3)
print('delta_v',mvs1,mvs2,'theoretical delta_v',tmvs1,tmvs2)

delta_v [0.002 0.09  0.037] [-0.001  0.067 -0.017] theoretical delta_v [0.002 0.092 0.038] [ 0.003  0.07  -0.017]


In [ ]:
# The complements economy used mean of 40 samples as it requires higher accuracy

In [13]:
va1c,va2c,va3c=get_vgap([50000,100000],[50000,40000],[10,20],100000,utility_func_c,[0.02,0.02,0])

1.019356573352196 2.0173356154168824 1.999603100845881 0.9806434266478041 1.9826643845831176 2.000396899154119
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
Gap 0.11035839223111532 0.005906342345109006 -0.0018736734740205652


In [14]:
vb1c,vb2c,vb3c=get_vgap([50000,100000],[50000,40000],[10,20],100000,utility_func_c,[0.02,-0.02,0])

1.0198527803709483 1.9791542155048394 2.000466484322425 0.9801472196290517 2.020845784495161 1.9995335156775749
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
Gap 0.135983212056205 -0.033896027108923144 0.0015274475038675739


In [15]:
va1c2,va2c2,va3c2=get_vgap([50000,100000],[50000,40000],[10,20],100000,utility_func_c,[0.02,0.02,0])

1.0201083936196205 2.020234932355069 2.0000061854666518 0.9798916063803798 1.9797650676449308 1.9999938145333485
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
Gap 0.11364528347871561 0.009252117699135365 -0.0023584774293099464


In [45]:
vb1c2,vb2c2,vb3c2=get_vgap([50000,100000],[50000,40000],[10,20],100000,utility_func_c,[0.02,-0.02,0])

1.019534547215707 1.9791542029337617 2.0006608009313487 0.980465452784293 2.0208457970662383 1.999339199068651
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
Gap 0.13372436001416865 -0.030903072639884455 -0.0015178924995480347


In [14]:
va1c,va2c,va3c=0.11035839223111532, 0.005906342345109006,-0.0018736734740205652
vb1c,vb2c,vb3c=0.135983212056205, -0.033896027108923144, 0.0015274475038675739
va1c2,va2c2,va3c2=0.11364528347871561, 0.009252117699135365 ,-0.0023584774293099464
vb1c2,vb2c2,vb3c2=0.13372436001416865 ,-0.030903072639884455 ,-0.0015178924995480347

In [19]:
mvc1=np.round(np.array([va3c+va3c2,va1c+va1c2,va2c+va2c2])/2,3)
mvc2=np.round(np.array([vb3c+vb3c2,vb1c+vb1c2,vb2c+vb2c2])/2,3)
tmvc1=np.round(np.array(np.dot(matrixc,[0,0.02,0.02])),3)
tmvc2=np.round(np.array(np.dot(matrixc,[0,0.02,-0.02])),3)
np.set_printoptions(suppress=True)
print('delta_v',mvc1,mvc2,'theoretical delta_v',tmvc1,tmvc2)

delta_v [-0.002  0.113  0.008] [-0.001  0.134 -0.032] theoretical delta_v [-0.001  0.113  0.01 ] [ 0.001  0.132 -0.029]
